AWSTemplateFormatVersion: 2010-09-09

Description: >
  This template creates a DynamoDB table.


Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Order_Details
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  OrdersTableName:
    Value: Order_Details
    Export:
      Name: BikeHubOrdersTable
  StatusIndexName:
    Value: StatusIndex
    Export:
      Name: BikeHubOrdersStatusIndex